export const ui = {
  zh: {
    resume: "简历",
    experience: "项目经历",
    about: "关于我",
    projects: "正在做的事",
    stack: "技术栈",
    contact: "联系我",
    explore: "查看项目",
    viewResume: "查看简历",
    resumeNote: "如果你对我的经历感兴趣，可以从这里了解更多。",
    contactNote: "欢迎聊聊想法、项目，或任何有意思的事情。",
    stackNote: "在项目中使用与探索的技术。",
    inProgress: "持续探索",
    implemented: "已有实现",
    source: "源码",
    evidence: "实现参考",
    projectIntro: "从想法到实现，留下可追溯的过程。",
    limits: "这里记录公开代码中的实现，不代表这些项目已经完成或上线。",
    profile: "个人简介",
    selected: "项目实践",
    home: "回到首页",
    notFound: "这条路还没有抵达。",
    notFoundNote: "你寻找的页面不存在，不如回到首页看看。",
    light: "切换浅色主题",
    dark: "切换深色主题",
    language: "Switch to English",
    github: "在 GitHub 找到我",
    availability: "保持好奇 · 持续探索",
    hello: "你好",
    iAm: "我是",
    niceToMeet: "，很高兴认识你！",
    playlist: "我的歌单",
    playPlaylist: "播放歌单",
    playlistSoon: "歌单整理中，晚点再来听～",
    playlistSource: "由网易云音乐提供",
    playlistFrame: "网易云音乐播放器",
    clock: "当前时间",
    calendar: "日历",
    weekdays: ["一", "二", "三", "四", "五", "六", "日"],
    credit: "设计灵感来自",
    navigation: "主导航",
  },
  en: {
    resume: "Resume",
    experience: "Projects",
    about: "About",
    projects: "Things I'm building",
    stack: "Stack",
    contact: "Let's connect",
    explore: "Explore projects",
    viewResume: "View resume",
    resumeNote:
      "If you're curious about my work, here's a little more about it.",
    contactNote:
      "Always happy to chat about ideas, projects, and interesting things.",
    stackNote: "Technologies I use and explore in my projects.",
    inProgress: "In progress",
    implemented: "Implemented",
    source: "Source",
    evidence: "Implementation",
    projectIntro: "From idea to implementation, with a traceable process.",
    limits:
      "These entries describe public code, not a claim that the projects are complete or live.",
    profile: "Profile",
    selected: "Selected work",
    home: "Back home",
    notFound: "This path hasn't been built yet.",
    notFoundNote: "The page you're looking for doesn't exist. Let's head home.",
    light: "Switch to light theme",
    dark: "Switch to dark theme",
    language: "切换为中文",
    github: "Find me on GitHub",
    availability: "Stay curious · Keep building",
    hello: "Hello",
    iAm: "I'm",
    niceToMeet: ", nice to meet you!",
    playlist: "My playlist",
    playPlaylist: "Play playlist",
    playlistSoon: "Playlist coming soon.",
    playlistSource: "Powered by NetEase Cloud Music",
    playlistFrame: "NetEase Cloud Music player",
    clock: "Current time",
    calendar: "Calendar",
    weekdays: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
    credit: "Design inspired by",
    navigation: "Main navigation",
  },
};
